---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - image: localhost:30500/nginx_test
        name: nginx-test
