---
apiVersion: v1
kind: Pod  # this is the object to be created by k8s
metadata:
  name: nginx    # name of our pod
  labels:
     what: what    # this is a label key:value
spec:
  containers:
  - name: nginx  # name of a container
    image: arm32v7/nginx # name and version of image to use
    ports:
    - containerPort: 80
