apiVersion: apps/v1
kind: Deployment
metadata:
   name: webservice
   labels:
     app: webby
spec:
  selector:
    matchLabels:
      app: webby
  replicas: 3
  template:
    metadata:
      labels:
        app: webby
    spec:
      containers:
      - name: webby
        image: zsoltszabo2007/webby   # REPLACE WITH YOUR WEBBY IMAGE
        ports:
        - containerPort: 8888  
